export interface CitySuggestion {
  name: string;
  country: string;
  popularity: number; // Higher is more popular
}

export const CITIES: CitySuggestion[] = [
  // Italy
  { name: "Roma", country: "Italia", popularity: 100 },
  { name: "Milano", country: "Italia", popularity: 95 },
  { name: "Napoli", country: "Italia", popularity: 90 },
  { name: "Torino", country: "Italia", popularity: 85 },
  { name: "Palermo", country: "Italia", popularity: 80 },
  { name: "Genova", country: "Italia", popularity: 75 },
  { name: "Bologna", country: "Italia", popularity: 80 },
  { name: "Firenze", country: "Italia", popularity: 90 },
  { name: "Bari", country: "Italia", popularity: 70 },
  { name: "Catania", country: "Italia", popularity: 70 },
  { name: "Venezia", country: "Italia", popularity: 95 },
  { name: "Verona", country: "Italia", popularity: 75 },
  { name: "Messina", country: "Italia", popularity: 60 },
  { name: "Padova", country: "Italia", popularity: 65 },
  { name: "Trieste", country: "Italia", popularity: 65 },
  { name: "Brescia", country: "Italia", popularity: 60 },
  { name: "Parma", country: "Italia", popularity: 60 },
  { name: "Taranto", country: "Italia", popularity: 55 },
  { name: "Prato", country: "Italia", popularity: 55 },
  { name: "Modena", country: "Italia", popularity: 60 },
  { name: "Reggio Calabria", country: "Italia", popularity: 55 },
  { name: "Reggio Emilia", country: "Italia", popularity: 55 },
  { name: "Perugia", country: "Italia", popularity: 60 },
  { name: "Livorno", country: "Italia", popularity: 55 },
  { name: "Ravenna", country: "Italia", popularity: 55 },
  { name: "Cagliari", country: "Italia", popularity: 65 },
  { name: "Foggia", country: "Italia", popularity: 50 },
  { name: "Rimini", country: "Italia", popularity: 70 },
  { name: "Salerno", country: "Italia", popularity: 60 },
  { name: "Ferrara", country: "Italia", popularity: 55 },
  { name: "Sassari", country: "Italia", popularity: 50 },
  { name: "Latina", country: "Italia", popularity: 50 },
  { name: "Giugliano in Campania", country: "Italia", popularity: 45 },
  { name: "Monza", country: "Italia", popularity: 60 },
  { name: "Siracusa", country: "Italia", popularity: 60 },
  { name: "Pescara", country: "Italia", popularity: 55 },
  { name: "Bergamo", country: "Italia", popularity: 65 },
  { name: "Forlì", country: "Italia", popularity: 50 },
  { name: "Trento", country: "Italia", popularity: 60 },
  { name: "Vicenza", country: "Italia", popularity: 60 },
  { name: "Terni", country: "Italia", popularity: 45 },
  { name: "Bolzano", country: "Italia", popularity: 60 },
  { name: "Novara", country: "Italia", popularity: 50 },
  { name: "Piacenza", country: "Italia", popularity: 50 },
  { name: "Ancona", country: "Italia", popularity: 55 },
  { name: "Andria", country: "Italia", popularity: 45 },
  { name: "Arezzo", country: "Italia", popularity: 55 },
  { name: "Udine", country: "Italia", popularity: 55 },
  { name: "Cesena", country: "Italia", popularity: 50 },
  { name: "Lecce", country: "Italia", popularity: 65 },
  { name: "Nardò", country: "Italia", popularity: 40 },

  // Europe
  { name: "Parigi", country: "Francia", popularity: 100 },
  { name: "Lione", country: "Francia", popularity: 80 },
  { name: "Marsiglia", country: "Francia", popularity: 80 },
  { name: "Nantes", country: "Francia", popularity: 70 },
  { name: "Bordeaux", country: "Francia", popularity: 75 },
  { name: "Nizza", country: "Francia", popularity: 85 },
  { name: "Londra", country: "Regno Unito", popularity: 100 },
  { name: "Manchester", country: "Regno Unito", popularity: 85 },
  { name: "Birmingham", country: "Regno Unito", popularity: 80 },
  { name: "Edimburgo", country: "Regno Unito", popularity: 85 },
  { name: "Berlino", country: "Germania", popularity: 95 },
  { name: "Monaco di Baviera", country: "Germania", popularity: 90 },
  { name: "Amburgo", country: "Germania", popularity: 85 },
  { name: "Francoforte", country: "Germania", popularity: 85 },
  { name: "Madrid", country: "Spagna", popularity: 95 },
  { name: "Barcellona", country: "Spagna", popularity: 100 },
  { name: "Siviglia", country: "Spagna", popularity: 85 },
  { name: "Valencia", country: "Spagna", popularity: 80 },
  { name: "Lisbona", country: "Portogallo", popularity: 90 },
  { name: "Porto", country: "Portogallo", popularity: 85 },
  { name: "Amsterdam", country: "Paesi Bassi", popularity: 95 },
  { name: "Rotterdam", country: "Paesi Bassi", popularity: 80 },
  { name: "Bruxelles", country: "Belgio", popularity: 90 },
  { name: "Vienna", country: "Austria", popularity: 90 },
  { name: "Praga", country: "Repubblica Ceca", popularity: 90 },
  { name: "Budapest", country: "Ungheria", popularity: 85 },
  { name: "Varsavia", country: "Polonia", popularity: 80 },
  { name: "Cracovia", country: "Polonia", popularity: 80 },
  { name: "Atene", country: "Grecia", popularity: 85 },
  { name: "Stoccolma", country: "Svezia", popularity: 85 },
  { name: "Oslo", country: "Norvegia", popularity: 80 },
  { name: "Copenaghen", country: "Danimarca", popularity: 85 },
  { name: "Helsinki", country: "Finlandia", popularity: 80 },
  { name: "Dublino", country: "Irlanda", popularity: 85 },
  { name: "Zurigo", country: "Svizzera", popularity: 85 },
  { name: "Ginevra", country: "Svizzera", popularity: 80 },

  // World
  { name: "New York", country: "USA", popularity: 100 },
  { name: "Los Angeles", country: "USA", popularity: 95 },
  { name: "Chicago", country: "USA", popularity: 90 },
  { name: "San Francisco", country: "USA", popularity: 95 },
  { name: "Miami", country: "USA", popularity: 95 },
  { name: "Las Vegas", country: "USA", popularity: 90 },
  { name: "Washington D.C.", country: "USA", popularity: 90 },
  { name: "Boston", country: "USA", popularity: 85 },
  { name: "Tokyo", country: "Giappone", popularity: 100 },
  { name: "Osaka", country: "Giappone", popularity: 85 },
  { name: "Kyoto", country: "Giappone", popularity: 90 },
  { name: "Nagoya", country: "Giappone", popularity: 80 },
  { name: "Pechino", country: "Cina", popularity: 95 },
  { name: "Shanghai", country: "Cina", popularity: 95 },
  { name: "Hong Kong", country: "Cina", popularity: 95 },
  { name: "Guangzhou", country: "Cina", popularity: 85 },
  { name: "Shenzhen", country: "Cina", popularity: 85 },
  { name: "Seoul", country: "Corea del Sud", popularity: 95 },
  { name: "Bangkok", country: "Thailandia", popularity: 95 },
  { name: "Phuket", country: "Thailandia", popularity: 90 },
  { name: "Singapore", country: "Singapore", popularity: 95 },
  { name: "Kuala Lumpur", country: "Malesia", popularity: 85 },
  { name: "Jakarta", country: "Indonesia", popularity: 80 },
  { name: "Bali", country: "Indonesia", popularity: 95 },
  { name: "Manila", country: "Filippine", popularity: 80 },
  { name: "Ho Chi Minh City", country: "Vietnam", popularity: 85 },
  { name: "Hanoi", country: "Vietnam", popularity: 80 },
  { name: "Sydney", country: "Australia", popularity: 90 },
  { name: "Melbourne", country: "Australia", popularity: 85 },
  { name: "Brisbane", country: "Australia", popularity: 80 },
  { name: "Perth", country: "Australia", popularity: 75 },
  { name: "Auckland", country: "Nuova Zelanda", popularity: 80 },
  { name: "Dubai", country: "Emirati Arabi Uniti", popularity: 95 },
  { name: "Abu Dhabi", country: "Emirati Arabi Uniti", popularity: 90 },
  { name: "Doha", country: "Qatar", popularity: 85 },
  { name: "Riyadh", country: "Arabia Saudita", popularity: 80 },
  { name: "Tel Aviv", country: "Israele", popularity: 85 },
  { name: "Istanbul", country: "Turchia", popularity: 95 },
  { name: "Ankara", country: "Turchia", popularity: 80 },
  { name: "Città del Messico", country: "Messico", popularity: 90 },
  { name: "Cancun", country: "Messico", popularity: 90 },
  { name: "San Paolo", country: "Brasile", popularity: 90 },
  { name: "Rio de Janeiro", country: "Brasile", popularity: 90 },
  { name: "Buenos Aires", country: "Argentina", popularity: 85 },
  { name: "Santiago", country: "Cile", popularity: 80 },
  { name: "Lima", country: "Perù", popularity: 80 },
  { name: "Bogotà", country: "Colombia", popularity: 80 },
  { name: "Toronto", country: "Canada", popularity: 90 },
  { name: "Vancouver", country: "Canada", popularity: 85 },
  { name: "Montreal", country: "Canada", popularity: 85 },
  { name: "Città del Capo", country: "Sudafrica", popularity: 80 },
  { name: "Johannesburg", country: "Sudafrica", popularity: 75 },
  { name: "Nairobi", country: "Kenya", popularity: 75 },
  { name: "Casablanca", country: "Marocco", popularity: 80 },
  { name: "Marrakech", country: "Marocco", popularity: 85 },
  { name: "Cairo", country: "Egitto", popularity: 85 },
  { name: "Mumbai", country: "India", popularity: 90 },
  { name: "Nuova Delhi", country: "India", popularity: 90 },
  { name: "Bangalore", country: "India", popularity: 85 },
  { name: "Mosca", country: "Russia", popularity: 90 },
  { name: "San Pietroburgo", country: "Russia", popularity: 85 },
  
  // Airports / Specifics
  { name: "London Heathrow (LHR)", country: "Regno Unito", popularity: 90 },
  { name: "Paris Charles de Gaulle (CDG)", country: "Francia", popularity: 90 },
  { name: "Frankfurt Airport (FRA)", country: "Germania", popularity: 85 },
  { name: "Dubai International (DXB)", country: "Emirati Arabi Uniti", popularity: 95 },
  { name: "Singapore Changi (SIN)", country: "Singapore", popularity: 95 },
  { name: "JFK Airport", country: "USA", popularity: 90 },
  { name: "Narita Airport", country: "Giappone", popularity: 85 },
  { name: "Malpensa", country: "Italia", popularity: 80 },
  { name: "Fiumicino", country: "Italia", popularity: 85 },
];
